language:
  - cpp
  - c
notifications:
  email: false
  irc: "chat.freenode.net#stepmania"

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libasound2-dev
      - libglew-dev
      - libmad0-dev
      - libpulse-dev
      - libva-dev
      - libvorbis-dev
      - libxinerama-dev
      - libxrandr-dev
      - yasm

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update      ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install yasm; fi

before_script:
  - cd Build
  - cmake ..
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}

script:
  - make -j2
