language: cpp
notifications:
    email: false
    irc: "chat.freenode.net#stepmania"

os:
  - linux
#  - osx

dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libasound2-dev
      - libglew-dev
      - libmad0-dev
      - libpulse-dev
      - libva-dev
      - libvorbis-dev
      - libxinerama-dev
      - libxrandr-dev
      - yasm


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update      ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install yasm; fi

before_script:
  - cd Build
  - cmake ..

script:
  - make -j2

#matrix:
#    include:
#        -
#            env: CXX_COMPILER=clang++-3.6 CC_COMPILER=clang-3.6 BUILD_TYPE=Release WITH_FFMPEG=OFF WITH_FFMPEG_JOBS=1
#            compiler: clang
#            addons: &clang36
#                apt:
#                    sources:
#                        - ubuntu-toolchain-r-test
#                        - llvm-toolchain-precise-3.6
#                    packages:
#                        - nasm
#                        - libudev-dev
#                        - clang-3.6
#                        - libmad0-dev
#                        - libgtk2.0-dev
#                        - binutils-dev
#                        - libasound-dev
#                        - libpulse-dev
#                        - libjack-dev
#                        - libc6-dev
#                        - libogg-dev
#                        - libvorbis-dev
#                        - libxtst-dev
#                        - libxrandr-dev
#                        - libglew-dev
#                        - libc++-dev
#                        - libstdc++-4.8-dev
#
#        -
#            env: CXX_COMPILER=clang++-3.6 CC_COMPILER=clang-3.6 BUILD_TYPE=Release WITH_FFMPEG=ON WITH_FFMPEG_JOBS=1
#            compiler: clang
#            addons: *clang36
#
#        -
#            env: CXX_COMPILER=g++-5 CC_COMPILER=gcc-5 BUILD_TYPE=Release WITH_FFMPEG=OFF WITH_FFMPEG_JOBS=1
#            compiler: gcc
#            addons: &gcc5
#                apt:
#                    sources:
#                        - ubuntu-toolchain-r-test
#                    packages:
#                        - nasm
#                        - libudev-dev
#                        - gcc-5
#                        - g++-5
#                        - libmad0-dev
#                        - libgtk2.0-dev
#                        - binutils-dev
#                        - libasound-dev
#                        - libpulse-dev
#                        - libjack-dev
#                        - libc6-dev
#                        - libogg-dev
#                        - libvorbis-dev
#                        - libxtst-dev
#                        - libxrandr-dev
#                        - libglew-dev
