language:
  - cpp
  - c
notifications:
    email: false
    irc: "chat.freenode.net#stepmania"

dist: bionic

addons:
  apt:
    packages:
      - libasound2-dev
      - libglew-dev
      - libmad0-dev
      - libpulse-dev
      - libva-dev
      - libvorbis-dev
      - libxinerama-dev
      - libxrandr-dev
      - yasm

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
    - os: windows
      script:
        - msbuild

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update      ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install yasm; fi

before_script:
  - cd Build
  - cmake ..

script:
  - make -j2
