language:
  - cpp
  - c
notifications:
  email: false
  irc: "chat.freenode.net#stepmania"

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Release
#  - BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libasound2-dev
      - libglew-dev
      - libmad0-dev
      - libpulse-dev
      - libva-dev
      - libvorbis-dev
      - libxinerama-dev
      - libxrandr-dev
      - nasm
      - libvdpau-dev
      - libxv-dev

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update      ; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install ffmpeg; fi

before_script:
  - cd Build
  - echo $LDFLAGS
  - export LDFLAGS=-mmacosx-version-min=10.13
  - echo $CFLAGS
  - export CFLAGS=-mmacosx-version-min=10.13
  - cmake ..
    -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}

script:
  - make -j2
