language:
  - cpp
  - c
notifications:
  email: false
  irc: "chat.freenode.net#stepmania"

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Release
#  - BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libasound2-dev
      - libglew-dev
      - libmad0-dev
      - libpulse-dev
      - libva-dev
      - libvorbis-dev
      - libxinerama-dev
      - libxrandr-dev
      - libvdpau-dev
      - libxv-dev
      - nasm
      - ninja-build
#      - libavcodec-dev
#      - libswscale-dev
#      - libavutil-dev
#      - libavformat-dev

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm; fi

before_script:
  - cd Build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CFLAGS=-mmacosx-version-min=10.13; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export LDFLAGS=-mmacosx-version-min=10.13; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_MAKE_PROGRAM=Xcode; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CMAKE_MAKE_PROGRAM=Ninja; fi
  - cmake .. -G${CMAKE_MAKE_PROGRAM}
    -DWITH_SYSTEM_FFMPEG=OFF
    -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}

script:
  - travis_wait cmake --build . --target ffmpeg_ext || true
  - cmake -U * ..
  - cmake ..
    -DWITH_SYSTEM_FFMPEG=OFF
    -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
  - cmake --build .
